# Generated by Django 3.1.6 on 2021-08-06 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='custmer',
            new_name='customer',
        ),
    ]
